print("Lauren's Top Five Movies\n1. Pulp Fiction\n2. Fight Club\n3. The Wolf of Wallstreet\n4. The Truman Show\n5. Us")
print("")
print("Lauren's Top Five Movies")
print("1. Pulp Fiction")
print("2. Fight Club")
print("3. The Wolf of Wallstreet")
print("4. The Truman Show")
print("5. Us")
